### PR TITLE
Call sysconf only at once

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by FreeSlave** [comment]
Should not PAGE_SIZE be __gshared, so it will be shared between all threads? By default global variables in D are thread-local, and using shared module consturctor you initialize it only in one thread.

**Comment by kubo39** [comment]
Yes, it should be. Thanks for pointing out!

**Comment by FreeSlave** [comment]
Needs a `@trusted` getter for __gshared variable. I'm not on Linux system now, so I can't ensure everything is alright.

**Comment by kubo39** [comment]
Ah, sorry. Fixed.

**Pull request merged**
